# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  #boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = ["kvm-intel" "wl"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/34ea8320-8dff-47b8-a2fc-bc8ddc55cadd";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/F4F5-537C";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/9c4740b0-dc3c-45cc-8195-970791a8f58b";}
  ];

  #  networking = {
  #    useDHCP = lib.mkDefault true;                        # Deprecated
  #    hostName = "doodle";
  #    networkmanager.enable = true;
  #    interfaces = {
  #      enp69s0 = {
  #        useDHCP = lib.mkDefault true;
  #      };
  #      wlp70s0 = {
  #        useDHCP = lib.mkDefault true;
  #      };
  #    };
  #  };

  # networking.interfaces.wlp70s0.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "on-demand";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.video.hidpi.enable = lib.mkDefault true;
}
